"""scripts/gen_stubs.py.

Generate minimal typed stubs for ``dino_datasets`` and ``dino_env``.

These stubs cover exactly the symbols imported by ``dino_loader`` — no more.
They are written to ``stubs/dino_datasets.pyi`` and ``stubs/dino_env.pyi``
relative to the repository root.

Usage
-----
    python scripts/gen_stubs.py          # regenerate both stubs
    python scripts/gen_stubs.py --check  # exit 1 if stubs are out of date

Design
------
The generator uses ``inspect`` to reflect the *installed* packages rather than
parsing source, so it always tracks the version that is actually installed in
the current virtual environment.  Running ``just gen-stubs`` after ``uv sync``
guarantees the stubs stay in sync.

Only the public symbols listed in ``_DINO_DATASETS_SYMBOLS`` and
``_DINO_ENV_SYMBOLS`` are emitted.  Everything else is intentionally omitted
to keep the stubs minimal and context-window-friendly.
"""

from __future__ import annotations

import argparse
import inspect
import sys
import textwrap
from pathlib import Path

# ── Repository root ────────────────────────────────────────────────────────────

_REPO_ROOT  = Path(__file__).resolve().parent.parent
_STUBS_DIR  = _REPO_ROOT / "stubs"

# ── Symbols to stub ────────────────────────────────────────────────────────────
# Keep these sorted and minimal — only what dino_loader actually imports.

_DINO_DATASETS_SYMBOLS: list[str] = [
    "CONFIDENTIALITY_LEVELS",
    "DEFAULT_STRATEGY",
    "ConfidentialityMount",
    "ConfidentialityRegistry",
    "Dataset",
    "DatasetConfig",
    "DatasetSpec",
    "GlobalDatasetFilter",
    "confidentialities_up_to",
    "get_confidentiality_mounts",
    "get_confidentiality_mounts_for",
    "get_registry",
    "register_confidentiality",
    "register_spec_migration",
    "resolve_path_for_confidentiality",
]

_DINO_ENV_SYMBOLS: list[str] = [
    "BW_THRESHOLD_GB_S",
    "CPU_STUB",
    "ClusterTopology",
    "DistribEnv",
    "Launcher",
    "LaunchContext",
    "configure",
    "configure_nccl",
    "detect_launcher",
    "detect_topology",
    "get_env",
    "get_local_rank",
    "get_local_world_size",
    "get_rank",
    "get_subgroup",
    "get_subgroup_rank",
    "get_subgroup_size",
    "get_world_size",
    "init",
    "is_distributed",
    "is_main_process",
    "is_subgroup_main_process",
    "new_subgroups",
    "save_in_main_process",
    "shutdown",
    "verify_interconnect",
]

# ── Stub generation ────────────────────────────────────────────────────────────

_HEADER = textwrap.dedent("""\
    # Auto-generated by scripts/gen_stubs.py — do not edit manually.
    # Regenerate with: just gen-stubs
    #
    # Minimal stubs covering exactly the symbols imported by dino_loader.
    # Only the installed package version is reflected here.

    from __future__ import annotations
    import enum
    from typing import Any, Callable, Literal, Sequence
    from pathlib import Path
    from datetime import timedelta
    from collections.abc import Iterator

""")


def _import_package(name: str) -> object:
    try:
        import importlib
        return importlib.import_module(name)
    except ImportError as exc:
        print(f"ERROR: cannot import {name!r}: {exc}", file=sys.stderr)
        print(
            f"       Ensure {name} is installed: uv sync",
            file=sys.stderr,
        )
        sys.exit(1)


def _get_obj(module: object, name: str) -> object | None:
    return getattr(module, name, None)


def _is_dataclass(obj: object) -> bool:
    import dataclasses
    return dataclasses.is_dataclass(obj) and isinstance(obj, type)


def _is_enum(obj: object) -> bool:
    import enum
    return isinstance(obj, type) and issubclass(obj, enum.Enum)


def _annotation_str(annotation: object) -> str:
    """Best-effort stringification of a type annotation."""
    if annotation is inspect.Parameter.empty:
        return "Any"
    
    if isinstance(annotation, type):
        raw = annotation.__name__
    else:
        raw = str(annotation)

    # Added "datetime." to the prefixes to handle timedelta
    prefixes = (
        "dino_datasets.", "dino_env.", "typing.", "collections.abc.",
        "pathlib.", "settings.", "dataset.", "datetime.", "<class '", "'>"
    )
    for prefix in prefixes:
        raw = raw.replace(prefix, "")
    
    # Map internal private names to Any
    if raw.startswith("_") and "|" not in raw: 
        return "Any"
    
    # Handle Union types containing internal names (e.g., Mount | _AnyMount)
    if "_" in raw:
        import re
        raw = re.sub(r'_[a-zA-Z0-9]+', 'Any', raw)
        
    return raw


def _stub_callable(name: str, obj: object, is_method: bool = False) -> str:
    """Emit a stub for a function or method."""
    try:
        sig = inspect.signature(obj)  # type: ignore[arg-type]
    except (ValueError, TypeError):
        return f"def {name}(*args: Any, **kwargs: Any) -> Any: ...\n"

    params: list[str] = []
    for i, (pname, param) in enumerate(sig.parameters.items()):
        # Skip 'self' or 'cls' for method stubs in .pyi files
        if is_method and i == 0 and pname in ("self", "cls"):
            params.append(pname)
            continue

        ann = _annotation_str(param.annotation)
        if param.default is not inspect.Parameter.empty:
            # We use ... for defaults in stubs
            params.append(f"{pname}: {ann} = ...")
        elif param.kind == inspect.Parameter.VAR_POSITIONAL:
            params.append(f"*{pname}: Any")
        elif param.kind == inspect.Parameter.VAR_KEYWORD:
            params.append(f"**{pname}: Any")
        else:
            params.append(f"{pname}: {ann}")

    ret = _annotation_str(sig.return_annotation)
    params_str = ", ".join(params)
    return f"def {name}({params_str}) -> {ret}: ...\n"


def _stub_class(name: str, cls: type) -> str:
    """Emit a stub for a class (dataclass, enum, or plain class)."""
    lines: list[str] = []

    if _is_enum(cls):
        lines.append(f"class {name}(enum.Enum):")
        # Enums in stubs usually show members as assignments
        for member_name in cls.__members__:  # type: ignore[attr-defined]
            lines.append(f"    {member_name} = ...")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append(f"class {name}:")

    # 1. Handle Fields (for Dataclasses)
    if _is_dataclass(cls):
        import dataclasses
        fields = dataclasses.fields(cls)
        for f in fields:
            ann = _annotation_str(f.type)
            if f.default is not dataclasses.MISSING:
                lines.append(f"    {f.name}: {ann} = ...")
            else:
                lines.append(f"    {f.name}: {ann}")
    
    # 2. Emit __init__ once
    try:
        # We look at the raw __init__ function to ensure 'self' is present
        init_stub = _stub_callable("__init__", cls.__init__, is_method=True).rstrip()
        lines.append(f"    {init_stub}")
    except Exception:
        lines.append("    def __init__(self, *args: Any, **kwargs: Any) -> None: ...")
    lines.append("")

    # 3. Emit public methods and properties
    for attr_name in sorted(dir(cls)):
        if attr_name.startswith("_") or attr_name == "__init__":
            continue
            
        try:
            # We check the class __dict__ to see if it's a static/class method descriptor
            raw_attr = cls.__dict__.get(attr_name)
            attr = getattr(cls, attr_name)
        except AttributeError:
            continue

        if isinstance(attr, property):
            ret = _annotation_str(
                attr.fget.__annotations__.get("return", inspect.Parameter.empty)
                if attr.fget else inspect.Parameter.empty
            )
            lines.append(f"    @property")
            lines.append(f"    def {attr_name}(self) -> {ret}: ...")
            lines.append("")
        elif callable(attr) and not isinstance(attr, type):
            is_static = isinstance(raw_attr, staticmethod)
            is_class = isinstance(raw_attr, classmethod)
            
            # --- THE FIX ---
            # If it's a classmethod, getattr() returns a bound method.
            # inspect.signature() on a bound method hides the 'cls' argument.
            # We must use .__func__ to see the original signature with 'cls'.
            target_obj = attr
            if is_class and hasattr(attr, "__func__"):
                target_obj = attr.__func__
            # ---------------

            if is_static:
                lines.append("    @staticmethod")
            elif is_class:
                lines.append("    @classmethod")
                
            stub = _stub_callable(attr_name, target_obj, is_method=(not is_static)).rstrip()
            lines.append(f"    {stub}")
            lines.append("")

    lines.append("")
    return "\n".join(lines) + "\n"


def _stub_constant(name: str, obj: object) -> str:
    """Emit a typed constant stub."""
    if isinstance(obj, tuple) and all(isinstance(x, str) for x in obj):
        return f"{name}: tuple[str, ...]\n"
    if isinstance(obj, str):
        return f"{name}: str\n"
    if isinstance(obj, (int, float)):
        type_name = type(obj).__name__
        return f"{name}: {type_name}\n"
    if isinstance(obj, dict):
        return f"{name}: dict[Any, Any]\n"
    return f"{name}: Any\n"


def generate_stub(package_name: str, symbols: list[str]) -> str:
    """Generate a complete .pyi stub for *package_name* covering *symbols*."""
    module = _import_package(package_name)
    lines: list[str] = [_HEADER]

    for name in symbols:
        obj = _get_obj(module, name)
        if obj is None:
            # Emit a safe fallback so the stub remains valid even if a symbol
            # was removed from the package.
            lines.append(f"# {name} not found in installed {package_name}\n")
            lines.append(f"{name}: Any\n\n")
            continue

        if isinstance(obj, type):
            lines.append(_stub_class(name, obj))
        elif callable(obj):
            lines.append(_stub_callable(name, obj))
            lines.append("")
        else:
            lines.append(_stub_constant(name, obj))

    return "".join(lines)


# ── Entry point ────────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    """Generate stubs and optionally check them for staleness."""
    parser = argparse.ArgumentParser(
        description="Generate minimal typed stubs for dino_datasets and dino_env.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated stubs differ from what is on disk.",
    )
    args = parser.parse_args(argv)

    _STUBS_DIR.mkdir(parents=True, exist_ok=True)

    targets: list[tuple[str, list[str], Path]] = [
        ("dino_datasets", _DINO_DATASETS_SYMBOLS, _STUBS_DIR / "dino_datasets.pyi"),
        ("dino_env",      _DINO_ENV_SYMBOLS,      _STUBS_DIR / "dino_env.pyi"),
    ]

    stale = False
    for package_name, symbols, dest in targets:
        print(f"Generating stub for {package_name!r} → {dest.relative_to(_REPO_ROOT)}")
        content = generate_stub(package_name, symbols)

        if args.check:
            existing = dest.read_text(encoding="utf-8") if dest.exists() else ""
            if existing != content:
                print(
                    f"  STALE: {dest.relative_to(_REPO_ROOT)} is out of date. "
                    "Run: just gen-stubs",
                    file=sys.stderr,
                )
                stale = True
        else:
            dest.write_text(content, encoding="utf-8")
            print(f"  Written {len(content)} bytes.")

    if stale:
        return 1

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
